spring:
  liquibase.enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/issue-tracker?useSSL=false&serverTimezone=UTC
    username: root
    password: Sanane.123
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl